apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production-eks-platform
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: production-eks-platform
spec:
  description: GitOps project for the Production EKS Platform workloads
  sourceRepos:
    - https://github.com/niks6996/Production-EKS-Platform.git
    - https://kyverno.github.io/kyverno
    - https://prometheus-community.github.io/helm-charts
    - https://aws.github.io/eks-charts
    - https://kubernetes-sigs.github.io/metrics-server/
    - https://kubernetes.github.io/autoscaler
  destinations:
    - namespace: platform
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: kyverno
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: kyverno.io
      kind: ClusterPolicy
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  orphanedResources:
    warn: true