apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-security-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: production-eks-platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production-eks-platform
  source:
    repoURL: https://github.com/niks6996/Production-EKS-Platform.git
    targetRevision: main
    path: policies/kyverno
    directory:
      recurse: true
      exclude: README.md
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - PruneLast=true
      - ServerSideApply=true